image: node:24

stages:
  - build
  - test
  - coverage
  - lint
  - prettier-check

cache:
  paths:
    - node_modules/

download_dependencies:
  stage: build
  script:
    - npm ci
    - npm run build

npm_test:
  stage: test
  script:
    - npm test

coverage:
  stage: coverage
  script:
    - npm run coverage

eslint:
  stage: lint
  script:
    - npm run lint

prettier-check:
  stage: prettier-check
  script:
    - npm run prettier-check
